### ISSUE TITLE
`npm run protractor` doesn't work on Mac OS X Yosemite machine

### ISSUE THREAD

**Issue by carusog** [angular/angular-phonecat#230]
Hi, trying to run protractor on Mac OS X Yosemite, node v0.12.0, npm 2.5.1 I get the following error (notice `[launcher] Error: Could not find chromedriver at /Users/papple/Devel/angular-phonecat/node_modules/protractor/selenium/chromedriver.exe
`):

```bash
angular-phonecat git:(96a9b5b) npm run protractor

> angular-phonecat@0.0.0 preprotractor /Users/papple/Devel/angular-phonecat
> npm run update-webdriver


> angular-phonecat@0.0.0 preupdate-webdriver /Users/papple/Devel/angular-phonecat
> npm install

npm WARN package.json karma-chrome-launcher@0.1.7 No README data

> selenium-chromedriver@0.0.2 install /Users/papple/Devel/angular-phonecat/node_modules/selenium-chromedriver
> node install

Downloading http://chromedriver.storage.googleapis.com/2.8/chromedriver_mac32.zip
Saving to /var/folders/41/0fkmgjl13lq332yk4l_fplbm0000gn/T/selenium-chromedriver115112-46057-c53p2z/chromedriver.zip
Receiving...
Received 781K...
Received 1564K...
Received 2346K...
Received 3128K...
Received 3967K...
Received 4749K...
Received 5531K...
Received 6313K...
Received 7096K...
Received 7878K...
Received 8311K total.
/var/folders/41/0fkmgjl13lq332yk4l_fplbm0000gn/T/selenium-chromedriver115112-46057-zqxgoo
Extracting zip contents
Writing location.txt file
Done. chromedriver binary available at /Users/papple/Devel/angular-phonecat/node_modules/selenium-chromedriver/bin/chromedriver

> angular-phonecat@0.0.0 postinstall /Users/papple/Devel/angular-phonecat
> bower install


> angular-phonecat@0.0.0 update-webdriver /Users/papple/Devel/angular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /Users/papple/Devel/angular-phonecat
> protractor test/protractor-conf.js

util.puts: Use console.log instead
Using ChromeDriver directly...
[launcher] Error: Could not find chromedriver at /Users/papple/Devel/angular-phonecat/node_modules/protractor/selenium/chromedriver.exe

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/papple/Devel/angular-phonecat/npm-debug.log
```

**Comment by jpaljasma** [comment]
I got it working by changing package.json

Set devDependencies.protractor to be "*", removed node_modules, ran `npm install` and `npm run update-webdriver`

**Comment by bjaanes** [comment]
I can confirm that the solution from @jpaljasma works.

**Comment by mannyfu** [comment]
I tried @jpaljasma 's approach but it didn't work for me.

**Comment by carusog** [comment]
@jpaljasma Thanks for your help, but it doesn't work here either.

**Comment by ereze** [comment]
Worked for me, thanks!

**Comment by sai29** [comment]
@jpaljasma How do I remove all the node_modules,? Should I just delete the node_modules folder or is there a command?

**Comment by bjaanes** [comment]
I just deleted the node_modules folder. It will be regenerated on npm install.

**Comment by sai29** [comment]
Thanks. It works fine when all the tests pass, but for a failing tests it shows which tests are failing and an error code 1  subsequently  exits with the same error as for @mannyfu above.

**Comment by skjolber** [comment]
I had the same problem running linux (fedora 21) and the solution from jpaljasma worked for me as well.

**Comment by hguiney** [comment]
@jpaljasma’s solution works for me on Mac OS X 10.9.5.

**Comment by mmadej** [comment]
works for me

**Comment by daple** [comment]
@jpaljasma’s solution works for me on Mac OS X 10.10.2 as well, thanks a lot!

**Comment by kevinhooke** [comment]
same issue, steps from @jpaljasma worked great - thanks!

**Comment by tintin34** [comment]
On macbook pro Yosemite, I solved the same error by downloading : https://sites.google.com/a/chromium.org/chromedriver/downloads manualy and copy in the good repertory. This error is due to a damage ZIP file.

I hope you'll resolve your problem.

**Comment by zanify** [comment]
I just followed @tintin34 suggestion and it worked for me, also on a mbp yosemite.
Was stuck with e2e test on the angular tutorial, downloaded the mac zip from the linked repository, unzipped it and put it in the ... /node_modules/protractor/selenium/ directory.

**Comment by ljelewis** [comment]
@tintin3's solution worked for me. I'm on Yosemite 10.10.2. The existing chromedriver zip file would not extract, but the 2.14 mac zip downloaded from http://chromedriver.storage.googleapis.com/index.html?path=2.14/ unzipped fine and protractor ran alright.

**Comment by jsphstls** [comment]
@tintin34 solution also worked for me.

I ran `npm run update-webdriver` after and received:

`
selenium standalone is up to date.
chromedriver is up to date.
`

**Comment by akm** [comment]
@tintin34 solution also works for me on Mac OS X 10.10.3 - thanks!

**Comment by mlg87** [comment]
thanks @jpaljasma! worked like a charm

**Comment by palerdot** [comment]
I had this same problem in Ubuntu. What worked for me
* `npm install chromedriver` - This installed the chromedriver in `angular-phonecat/node_modules/protractor/node_modules/chromedriver`
* copy the zip file from the `lib` directory from the above installed location and put it in `/angular-phonecat/node_modules/protractor/selenium/`
* unzip the copied zip file to extract the binary. Now run `npm run protractor`

The problems for me seems to be invalid chromedriver zip file in `/angular-phonecat/node_modules/protractor/selenium/`. Getting the correct zip file and extracting the binary solved the issue. 

There seems to too much issues on this on different OSes. Angular team should make a better documentation on this problem.

**Comment by karlli1976** [comment]
Thanks you @jpaljasma , your solution works for me :-)

Yosemite: 10.10.3

**Comment by gnarmedia** [comment]
Thanks @jpaljasma, solution worked, Ubuntu 14.04

**Comment by ygarbage** [comment]
Thanks @jpaljasma, it worked on Debian 7.8.

**Comment by nickleus** [comment]
@tintin34 thx :) downloaded the zip to ~/Downloads
unzipped it
copied the file "chromedriver" to folder /*path-to-*/angular-phonecat/node_modules/protractor/selenium/

**Comment by tintin34** [comment]
You're welcome :)

**Comment by halfzebra** [comment]
I have managed to fix similar issue by updating Java.

**Comment by mayra-cabrera** [comment]
Thanks @tintin34! Your solution works on OS X 10.10.3 :)

**Comment by machinefixer** [comment]
@jpaljasma 's solution works for me, thx!

**Comment by warles34** [comment]
@tintin34 solution solved my problem, and looks more solid and safe =D

**Comment by rockallite** [comment]
The version of Protractor specified in ```package.json``` of AngularJS tutorial is ```1.0.0``` (by the ```~1.0.0``` indicator), which has a bug downloading and unzipping selenium webdrivers. See Protractor [issue #1005](https://github.com/angular/protractor/issues/1005).

Without the webdrivers, you can't do end to end test.

Change the version of Protractor to ```1.8.0``` or ```2.1.0```, then run ```npm update```. This will resolve the problem.

**Comment by alecsandre** [comment]
Hi.
Had same issue. I am using Windows 8.1.
@rockallite solution worked for me.
Before that i tried @jpaljasma and @tintin34 solution, but no results.

After i changed Protractor version to 1.8.0 in package.json. When i run 'npm run protractor' i recieved an warning 'chromeOnly is deprecated. Use directConnect: true'. In 'protractor-conf.js' i removed 'chromeOnly' and put 'directConnect: true'.

That is how i fixed. Thanks @rockallite.

**Comment by caseytrombley** [comment]
this worked for me as well after doing this step:

edit this file: 
node_modules/protractor/package.json and change the minijasminenode dependency to <1.0.0 so it now reads like this:
"minijasminenode": "<1.0.0",

**Comment by javiercriado** [comment]
the solution that worked for me was editing /angular-phonecat/test/protractor-conf.js file and changing "chromeOnly: true" to "chromeOnly: false"
(I'm using linux ubuntu)

**Comment by srimola** [comment]
Mac OS 10.10.5
Angular 1.4.0-rc.1
Protractor 2.1.0

In `protractor-conf.js`, I removed `chromeOnly: true` and replaced with `directConnect: true` as per @alecsandre 's comment. This fixed it for me.

**Comment by julsgud** [comment]
@jpaljasma 's solution fixed it for me. On Mac OS Yosemite 10.10.5

**Comment by jackwhit3** [comment]
On OS X Yosemite 10.10.2
I have a different error message than yours, see #276 .
But @alecsandre 's solution works for me.
Protractor version doesn't seem to matter, I had v2.3.0 all the way.

**Comment by wojciechpe** [comment]
@alecsandre 's solution worked for me in Windows 10 64b

**Comment by frak** [comment]
Thanks @alecsandre - your solution worked for me

**Comment by AshCoolman** [comment]
I had to ensure I run `webdriver-manager update` from the version being used in the npm module e.g.
`./node_modules/protractor/bin/webdriver-manager update`

**Comment by amandaol** [comment]
@alecsandre fix worked for me. Thank you!

**Comment by jasunde** [comment]
On Mac OS X 10.11.1 I find that replacing `chromeOnly: true` with `directConnect: true` in `test/protractor-conf.js` solves the error without any additional `npm update-webdriver`.

**Comment by amaechler** [comment]
@jasunde fix worked for me.

**Comment by McAlyster** [comment]
@jasunde fix worked for me

**Comment by stevenluong** [comment]
@jasunde fix worked for me as well,thanks !

**Comment by DanielJurkovic** [comment]
@jasunde fix worked for me on Windows 10 x64

**Comment by RamadanPajaziti** [comment]
@tintin34 or now @valsouche solution worked for me. Tried almost every other solution but without luck.
If you dont have selenium folder under protractor(like me), then create a folder with that name and paste chromedriver in there. Try this solution before others. It will save your time, belive me.

**Comment by chadlajeunesse** [comment]
@jasunde fix also worked for me, thanks.

**Comment by jonathanboswell** [comment]
So spent a good bit of time looking into "Why?" @jasunde fix works.

In the office here we have Linux and Mac workstations. The default path to Chrome binary in Linux is /usr/bin/google-chrome and in OSX 10.10 it's /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome 

When 'npm install' builds 'node_modules' and if that folder gets added to the Git repository of a project where users have different operating systems, protractor isn't able to find the Chrome executable.

**Comment by gkalpak** [comment]
And that's a good examples of the reasons why one should not commit the `node_modules/` directory :smiley:

**Comment by jonathanboswell** [comment]
Totally @gkalpak! And we fixed that stat on the dev's repository who had done that

**Comment by kematzy** [comment]
@jasunde fix worked for me on Mac OS X 10.11.3 (El Capitan) with node 5.0.0. Thanks a lot!

**Comment by mbis123** [comment]
Hi,

Just to say that I had to set "directConnect: true" in the protractor-conf.js file AND change my localhost to 127.0.0.1:8000 (probably because I have not set the 127... to 'localhost' in my hosts file)

Thanks guys helped a lot!

**Comment by jquerygeek** [comment]
Still having the same issue as mentioned by @mannyfu 
works fike when test pass, but getting error with failed test. 
any idea? @jpaljasma

**Comment by carrigmore** [comment]
I find add sudo at the begin of the command will resolve the problem.

**Comment by schandra-rpx** [comment]
chromeOnly: true,
directConnect: true

this worked for me in osx 10.11.5

**Comment by gkalpak** [comment]
@schandra-rpx, ooc is `chromeOnly: true` necessary? Afaict, the version of protractor used in the tutorial only cares about `directConnect: true`.

**Comment by norbertes** [comment]
I was able to run via `protractor ./test/protractor.config.js`, but couldn't make it from `npm run test-e2e` (which had the same command as I was using in command line).

@AshCoolman fix worked for me OSX El Capitan (10.11.4)
